### PR TITLE
feature: send referenced fields stats to apollo studio

### PR DESCRIPTION
**Pull request by gilach**
Fixes needed after apollo-server-core introduced breaking change in v3.6.0

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
This may fix the build, but will it keep the library functional? In other words, won't we have to provide something in this new field?

**Comment by gilach** [comment]
I've checked the source code of the change introduced in `apollo-server-core`. Providing null will basically run the same logic as before the change, it just won't execute additional stuff introduced in v.3.6.0.

**Comment by simoneb** [comment]
apart from not breaking anything let's see if there's an opportunity to actually leverage those new features. if not at the current time, let's consider creating an issue to implement support for them in the future

**Comment by gilach** [comment]
I've managed to add functionality to our plugin so that it calculates and sends referenced field stats the same way apollo's usageReport plugin does. Tested that against Apollo Studio and it looks to work fine.

More info on the referenced fields and the change introduced in `apollo-server-core` here:
https://github.com/apollographql/apollo-server/commit/17c621101e7e62254b95cad981872da7d0cee870

**Review by simoneb — COMMENTED** [review]
We need a test which tests a case when there is something in this new property, not just an empty object

**Comment by gilach** [comment]
Test added.

**Comment by simoneb** [comment]
@radomird @gilach is this waiting for something to be merged, apart from the linked issue failure?

**Pull request merged**
